# Generated by Django 4.2.13 on 2024-05-29 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
